from .home import home
from .category import category
from .myarticles import myarticles
from .detail import article_detail
from .contact_send import contact
from .addingarticle import add_article
from .edit_article import edit_article
from .delete_article import delete_article
from .delete_comment import delete_comment